- metrics_gather.sh
- rd_tool.py
- transfer_git.sh
The assumption is that Daala takes longer to encode -v 1 than larger -v
settings
> Speed up queue by doing long jobs first

- metrics_gather.sh
- rd_tool.py
I noticed that the working encodings were being routed to /dev/null, so I added it to vpx.
Added white-space formatting to last few statements in file too.
> Possible vpx fix?

- rd_tool.py
- sets.json
I added sing_irene_short, it was missed out of the json list for some reason?
> Implement efficient file ordering for AWS job allocation

- rd_tool.py
Short-circuits sometimes-unnecessary polling code. Some extra comments too.
> Streamlining

- rd_tool.py
Use self.machine.host as TD advised.
> Use self.machine.host as TD advised.

- awsremote.py
- rd_tool.py
- scheduler.py
- utility.py
Seems to work correctly. Slowing down the connection rate fixed the network dropping. I was wondering about unused imports so I ran a lint and removed all the extra ones.
I'm not sure what you think about `get_time` vs `GetTime` but it seems more consistent. The rest is just nitpicks pointed out by the linter.
> Python 2 to Python 3

- ab_meta_compare.sh
- rd_tool.py
Here I updated rd_tool to use ab_meta_compare.sh instead of daala including it.
> Add ab_meta_compare to rd_tool instead of daala

- rd_tool.py
- utility.py
Incidentally, fixes a crash in the IndexError exception handler.
> rd_tool: add wrapper for print that prepends get_time()

- rd_tool.py
- sshslot.py
- transfer_git.sh
Added the work_root field into the machine json file so the working directory can be set up somewhere other than /home/ec2-user (although it still defaults there, so aws should stilll work).
> Add work_root parameter and fix up hardcoded ec2 names

- rd_tool.py
Gives "at quality 5 failed!" instead of "at quality 5failed!"
> rd_tool: fix error msg format

- metrics_gather.sh
Use two dashes before cpu-used and use ivf like high delay vp9 and
av1-rt.
> Fix vp9-rt settings

- metrics_gather.sh
- sshslot.py
- work.py
Hi,
This commit adds support for running the https://github.com/divideon/xvc codec on AWCY.
/Per
> Add xvc codec support

- rd_server.py
- rd_tool.py
- sshslot.py
- work.py
This makes few path configurable using environment variables instead of using the hardcoded/relative ones.
> Configuration improvements

- metrics_gather.sh
use enc-mode 0, set intra-period
> SVT-AV1: update default command line

- metrics_gather.sh
This updates svt-av1 to always run single threaded.
> SVT-AV1: run single-threaded by default

- metrics_gather.sh
- rd_server.py
Tested on a local AWCY instance.
> Return a no-retry exit code on rav1e decode errors

- metrics_gather.sh
When running the Random Access (RA) CTC, each input file of 130 frames
is encoded as two separate GOPs of 65 frames in parallel and the
resulting OBU files are merged before processing.
This patch forces --limit=130 to prevent users from overriding this
parameter and producing invalid output.
> Add GOP parallelism to the Random Access (RA) CTC.

- metrics_gather.sh
The Adaptive Streaming (AS) configuration produces binary exact OBU
files as the same Random Access (RA) configuration.
This patch enables GOP parallelism for Adaptive Streaming (AS) runs.
> Use GOP parallelism with av2-as configuration.

- metrics_gather.sh
When running the Adaptive Streaming (AS) configuration, all files which
are not 3840x2160 are upsampled to 3840x2160 via HDRConvert just after
decoding from OBU to Y4M and the reference file is changed to the
3840x2160 uncompressed input file.
Due to HDRTools requiring all OutputFile parameters to be explicitly
specified (as opposed to just copying the SourceFile parameters), this
path will temporarily create two extra copies of the 3840x2160 output
which at 130 frames 4:2:0 is 3.1GB (!) per copy.
> Add 3840x2160 resampling via HDRConvert to av2-as.

- metrics_gather.sh
- work.py
Also fixes a bug where we would only use the last line of the CSV
output for the pooled results.
> Switch libvmaf output parsing to use the XML output format.

- sets.json
It is useful to quickly debug the scenechange detection tools.
> Add a scaled down vimeo-corpus-10s

- sets.json
Reverts xiph/rd_tool#111
Argh, it claimed it was going to merge into my own master fork. Sorry about that.
> Revert "sets.json: File is 'dark720p_xxx' not 'dark70p_xxx'"

- metrics_gather.sh
- rd_server.py
- sets.json
- work.py
This commit introduces option to parse multiple sets, together,
For average, we are doing the first set value at the moment.
The mandatory set is Preset Adaptive, so during runtime, it changes
based on the CTCv3 Requirements.
~Once Previous MR #120 is merged will rebase on top of that.~
Merged MR #120 changes to be in commit 185fc87198f8406590f51e852563db6fe35470fa
> server: Introduce multiSet Parser and migrate to CTCv3

- rd_server.py
- work.py
This introduces additional layer of structure in the encode_job folder if there are more than 1 Preset required to encode for a given job.
Tested locally with VLC12 to keep mostly backward compatible.
> server: Introduce Multiconfig encode jobs

- metrics_gather.sh
- work.py
This is for AOM-CTC conditions, 
We require to have perf installed in dockers and host machines should have support to do perf stat without root.
> Compute MD5 and EncCycles, EncInstrs with Perf

- metrics_gather.sh
- work.py
We require to measure decoding perf cycles along with encoding
This was missed to push along with previous Patchset
> work: Use Perf for decoding jobs

- rd_server.py
This uses Xiph's mailfish for doing SMTP based authentication,
SMTP configuration should be written in the `smtp_cfg.json` file inside conf location.
Example smtp_cfg.json,
```json
{
"smtpserver"  : "mailfish.xiph.org",
"sender"      : "awcy-noreply@xiph.org",
"username"    : "USERNAME",
"password"    : "PASSWORD"
}
```
> server: Introduce SMTP based email logging service

- rd_server.py
Before this commit, user gets an error when smtp_config is not present.
> server: Warn users if smtp_cfg is not present

- rd_server.py
This handles buildfailed email notification,
The API is,
$RD_SERVERURL:$PORT/?fail_job_notifier?run_id=$ID&failtype=$type&nick=$email Sample:
http://172.17.0.3:4000/fail_job_notifier?run_id=avm_base_3.1_test_A3_IDR_6QP_JOB_T&failtype=buildfailed&nick=mindfreeze@videolan.org
> server: Introduce FailNotifier API endpoint

- metrics_gather.sh
- rd_server.py
This helps to get the numbers of perf and copybook the stdout.
> metrics_gather: Add Perf for AVM GOP Parallel, and remove A1 for LD

- metrics_gather.sh
- sshslot.py
- work.py
This is based on vvc-vtm-ra-ctc preset but with AOM_CTC AS way,
This commit also adds Tiling option for VVC_VTM for >=4K resolution
> work: Add VVC-VTM for AS config

- metrics_gather.sh
We have to exclude chroma-format 420mpeg2 due to a bug in upstream,
Decoding y4ms do not retain frame-rate of input. Due to some SEI storage reasoning, so currently best to decode to YUV, and then convert to Y4M If decoding to Y4M from bitstream is needed, we need to have `--HrdParametersPresent=1 --SEIPictureTiming=1 --SEIBufferingPeriod=1 --RCCpbSize=1000` as parameters.
Upstream ticket tracker for 420mpeg2: https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/1598
> metrics_gather: Migrate to Y4M encode pipeline for VVC-VTM

- rd_server.py
When email notification was introduced, we missed to handle this and it was not noticed.
> server: Fix the corner case of multiSets average generation

- rd_server.py
- work.py
This is designed carefully after multiple iteration and testing, yet this will run ~15 hours (usertime) with ~4/5 machines with some sets (A1, A2, B1) taking 3 threads each for AOM-CTCv4.0.
> AOM: Introduce AVM Nightly configuration

- metrics_gather.sh
We do with libvmaf, and they are stable + part of AOM-CTC, so let us save the CPU cycles
> metrics_gather: Stop computing dump* daala_metrics

- rd_server.py
> Nightly Testing Tweaks

- metrics_gather.sh
- rd_server.py
- work.py
Main changes are
+ 2x2 tiling for E/G1 in RA
+ 10bit for A2/A4/B1
+ SCC tune for B2; SC detector on for others
+ VMAF to 3.0 and using aom_ctc v6.0 in CLI
> work: Migrate to CTCv6

- metrics_gather.sh
> Guard INTRA_PERIOD for VVC-RA, fix metrics for siwg-ctc-svt-av1

- metrics_gather.sh
- sets.json
> VVC CTCv6 Updates

- rd_server.py
Not sure if we need to have a variable which we never use or clear
This might close #168
> server: Stop having work_done variable
