pylib/encoders.py, pylib/executor.py, pylib/metrics.py, pylib/y4m.py, rd_tool_json.py, tasks/encoder_version.py, tasks/run_encoder.py, tasks/y4m_info.py
Hello,
I mentioned on IRC that I would like to see JSON output and target rate search in rd_tool, to allow for AWCY features like visual comparisons.
This is a tentative implementation. Remote execution is not implemented yet, but the design is intended to work for the same use cases as today. I figured it would be good to check if this looks useful before going further with this.
The improvements on the current rd_tool are:
- Output data is JSON, making it easy to add new fields. ([Example output](https://gist.github.com/unbounded/3a3c264d01ddfbe36f8c) for a set with a single file.)
- The tool can do a binary search to find an encode with a desired target rate. All the qualities tried in the binary search are added to the output.
Cons I see are:
- Binary searching results in more total …
=> rd_tool with JSON output

rd_tool.py, sets.json
This seems to work well. Works with video and with pictures. Exports the pictures or videos to `../runs/...` where the directory structure is the same as awcy uses except that the files go into subfolders called `bpp_0.1` or whatever the bpp value happened to be. The random network failure seems gone (I've run it with up to 500 pictures at a go). I think slowing that sleep timer down fixed it.
It requires daala ab scripts be updated so I'll go ahead and submit a PR for that.
@tdaede This seems to work well so I'd expect the next step is to get awcy to where it can fire off a build set?
=> Get abwork working better

rd_tool.py
Was always hitting "Unsupported Mode error"
=> rd_tool: fix 'metric' mode

rd_tool.py
Fixes "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8211: ordinal not in range(128)"
=> rd_tool: default to utf-8 when loading sets

metrics_gather.sh
Use a single awk process to sum to columns from the $TIMER_OUT file.
N.B. only tested locally on a dummy file.
Cc: @tmatth
=> metrics_gather: simplify ENCTIME calculation

metrics_gather.sh
Since TIMER_OUT didn't exist, this was always setting ENCTIME to 0.
=> metrics_gather: fix env variable

rd_server.py, scheduler.py, sshslot.py, work.py
Prevents cancelled running work from being restarted.
Stops work that is being cancelled from having slot.kill call kill on a previous work's subprocess (or None). slot.kill now spawns a thread that will wait for slot.start_shell to be called.
Fixes an unlikely race condition where slot.kill kills a future work's subprocess.
Fixes an unlikely race condition where a work.cancel checks for a slot, but the slot is set to None before slot.kill is called.
=> Fix killing work that is running.

metrics_gather.sh
Earlier, this variable was assigned, which would have rewritten any earlier values ('-S' right now).
We should concat the string variable instead.
=> metrics_gather: Append AOMDEC_OPTS

metrics_gather.sh
Drops `mv: cannot stat 'core.*': No such file or directory`
=> metrics_gather: silence non-error

README.md, metrics_gather.sh
If dav1d is missing, fall back to `aomdec`. This replaces the current method of comparing with the encoder reconstruction.
=> Use decoder output (dav1d or aomdec) for rav1e BD rate computation and assert that it is equal to reconstruction output

metrics_gather.sh
Without this, every decoded frame will generate
an extra line of output in case of a desync.
=> Make dav1d decode quietly

metrics_gather.sh, rd_server.py
Though I thought I had tested it properly it seems to cause runtime errors. I will submit a new PR to implement that functionality, tested more thoroughly.
=> Revert "Return a no-retry exit code on rav1e decode errors (#53)"

metrics_gather.sh, rd_server.py
The decoders are now optional dependencies.
In case no decoder is installed, bitstream
testing will be skipped, and a message will
be logged.
Tested on my instance with both a working and a broken commit, seems to work as intended.
I'm not actually sure why it was failing before. It may not have been due to the return code patch.
=> Use installed decoders to test rav1e bitstream

sshslot.py
Fixes "protocol error: filename does not match request" error.
=> Add -T flag to SCP command

metrics_gather.sh, work.py
* Fix the format set for 10-bit 4:2:0
* Update the default $VMAFOSSEXEC path
* Update the VMAF command line
* Fix VMAF extraction expecting garbage preceding the score
* Parameterize the VMAF model name
=> Update and fix issues in VMAF implementation

metrics_gather.sh
Fields in the Y4M header can appear in any order and this patch parses
them based on their leading character.
=> Correctly parse Y4M header.

metrics_gather.sh
When running the Random Access (RA) CTC, each input file of 130 frames
is encoded as two separate GOPs of 65 frames in parallel and the
resulting OBU files are merged before processing.
This patch forces --limit=130 to prevent users from overriding this
parameter and producing invalid output.
=> Add GOP parallelism to the Random Access (RA) CTC.

metrics_gather.sh
The av2-ra, av2-ra-st and av2-as CODEC profiles all share the same
Random Access (RA) encoder configurations.
=> Merge av2-as with av2-ra and av2-ra-st profiles.

rd_server.py
The free_slots array is used as a stack, this patch reverses the order
so machine slots are filled in lexicographic order on AWCY restart.
=> Reverse free_slots order for initial machine list.

sets.json
Remove Matinkaaren_silta.y4m and KellermanBallfieldMefisto.y4m images
from av2-f1-hires and av2-f2-midres test sets respectively.
=> Update thte still image test sets to match AV2 CTC.

metrics_gather.sh
In theory we can go up to about 13GB, but be conservative.
=> Increase ram limit to 8GB.

sets.json
simple typo was causing this file to fail.  Verified it is in fact named 'dark720p_xxx' in the sets offered for download.
=> sets.json: File is 'dark720p_xxx' not 'dark70p_xxx'

sshslot.py
We aren't parsing w/ a shell, so the quotes trigger errors related to
non-literal parsing in scp. Adding -T would fix these issues, but we
can switch to using rsync instead.
When rsync fails, it's more verbose than scp. Unfortunately,
metric_gather.sh does not currently produce all of the files that are
being requested for rav1e/other codecs. This means there is some amount
of spam produced in those logs.
=> Replace scp with rsync and remove quotes

rd_server.py
This is a minor cosmetics fix for having total.out rendering correctly for Mandatory case.
=> server: Use A2 Class as prefix for Mandatory/All CTC case

sshslot.py
The AWCY started to build static builds of SVT-AV1
=> sshslot: Copy only SVT-AV1 binary

metrics_gather.sh, rd_server.py
This patchset contains two fixes, 
a) Fixes F1/F2 Class Encoding, this was not accounting
- `--limit=1`
- `av2-f` Quality, we change the Quality on the fly during creation of each RDRun for these specific sets, which is most optimal and fast way. 
b) Tick tweaks, so there is an edge case where some of the inital jobs in the list finishes before others, tick logs things multiple times but only compute total.out once, which is not correct, so we break the tick into 3 parts.
=> Server: Fix Still Image Encoding and Tick tweaks

work.py
As the job lists is getting bigger and bigger, it is better to have a buffer-time before we try to copy.
For some big jobs, we are hitting copy-back error, lets try this first.
=> work: Add some delay before the copy-back action

sshslot.py
This is a specific-rsync issue where some files are not copied back, and adding protect-args to make sure the rsync/remote do not do weird file-handling,
Man-page:
> -s, --protect-args
> This option sends all filenames and most options to the remote rsync without allowing the remote shell to interpret them.
=> sshslot: Remove shell-quotes for filenames

cfg/vvc-vtm/encoder_intra_vtm.cfg, cfg/vvc-vtm/encoder_lowdelay_vtm.cfg, cfg/vvc-vtm/encoder_randomaccess_vtm.cfg, metrics_gather.sh, sshslot.py, work.py
This PR adds support to encode/decode/compute metrics for VVC-VTM for 
+ RA
+ AI
+ LD
+ RA GOP Parallel
Tested locally with VLC12, the QPs and things are strictly as per JVET_CTC, so it might be incompatible to do apple-apple comparision with AOM/AVM. So we would require to fine-tune the preset options.
=> Add VVC-VTM support

rd_server.py
We are handling them at the server(AWCY) side, so we do not need to touch the prefix, so assume that task is always correct.
=> server: Avoid re-allocation of prefix

metrics_gather.sh
We are not assigning QPs when no preset is given, this is a regression from 55d1812b4cd466711533f6aae5335872a392b95e
=> metrics_gather: Fix default SVT_AV1 QP assignment

rd_server.py, work.py
Two things
a) Fix still image encoding, as they have different QPs, and have to make sure the limits from CLI is override with --limit=1 else  the Bits will be different
b) Copy back Encoding/Decoding time files, this is mainly useful to track down the encoding/decoding commands for better debugging of a run.
=> Fix Stil Image CTC encodes and copy Encoding/Decoding files

rd_server.py, work.py
Make sure we kill all the jobs in the list, since we are having more than one runs for a given run_id due to set and preset nature. 
This PR also addresses small bug-fix for av2-all allocation which did not work all the time.
=> server: Iteratively remove jobs on cancellation and allocate av2-all correctly

cfg/vvc-vtm/encoder_randomaccess_vtm_gop16.cfg, metrics_gather.sh, sshslot.py, work.py
Introduce a VVC configuration which is close to AOM-CTC's RA configuration, main changes over VVC-CTC-RA
+ Use Parallel GOP by default, as VVC do not allow non-multiple of GopSize for IntraPeriod (we can only do 64, not 65)
+ Use Closed-GOP config, IDR (DecodingRefreshType=2)
+ Use GopSize as 16, encoder_randomaccess_vtm_gop16.cfg
+ Set IntraPeriod as -1, this is for having only 1 I-Frame in every 65 Frames
=> metrics: Introduce VVC VTM RA CTC

rd_server.py
This introduces an iteractive tracker which iterates through the list of running jobs and see if there is same run_id (ie. multi config/sets), then have a common counter for the job. Useful for time-estimator in big picture.
In the current logic, the counter will reset if a set is completed and recomputes.
Strictly speaking it is really running job tracker.
=> server: Introduce new runnnig job tracker

metrics_gather.sh
This was a bug which went unnoticed where the perf timing is recomputed, for GOP parallel encodes. We compute them two files, and save it, so gracefully guard and skip it.
=> metrics_gather: Only read perf-data for sequential encodes

rd_server.py, sshslot.py, work.py
This introduces the dynamic allocation of slots for a given job. 
Allocate 1/2 slots based on resolution and job type. 
~Current problem: Slots once removed from free are not allocated at second time. This could be due to a manual rewrite of free_slots.~
Screenshot of machine_usage: 
Edit:
Motivation: 
Currently many jobs (eg. AVM's RA with >4K resolution), we use multithreaded, and we do not have a clever way to allocate slots to make sure we are not exceeding/throttling machines. We used to have arbitrarily 56 slots on 112 machines (for VLC1,2,3) as a worst-case guess. So it just works. but we are losing a lot of CPU resources. 
This PR introduces a pre-check and allocates one more slot for a job which requires >1 slots
Edit2:
The latest iteration also includes handling of Parallel-GOP …
=> Improve Multislot handling

sets.json
This is for AVM and AOM testing
All of them are 6s/10s long sequences
=> sets: Add aomctc-subjective-long set

metrics_gather.sh, rd_server.py, work.py
CTC v7.0 includes notable threading changes, making AS optional,
1. 4 Column tiles for A1, E, G1 in RA
2. 2 Column tiles for A2, B1 in RA
3. 2 Column, 1 Row tiles (8) for A2, B1 in LD
4. 2 Column tiles for A3 in LD
5. 15 Frames in AI
6. AS is Optional
6.1 4 tiles for 2K, 4K (3840x2160, 2560x1440)
6.2 2 tiles for 1080p (1920x1080)
6.3 1 tiles for 720p and below (1280x720, 960x540, 640x360)
TODO
+ Verification Test mode
+ Memoery Reporting method
=> server: Migrate to AOM CTCv7.0 
